blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions & Feature request
    url: https://github.com/am-abudu/Qexo/discussions
    about: Use GitHub discussions for message-board style questions and discussions or feature request.